# Generated by Django 3.1.5 on 2022-03-16 06:11

from django.db import migrations, models
import django.db.models.deletion
import myfinal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=myfinal.models.file)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ownerform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownername', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('ownerpin', models.PositiveIntegerField(default=0)),
                ('housecategory', models.CharField(max_length=100)),
                ('housename', models.CharField(max_length=100)),
                ('division', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chattogram', 'Chattogram'), (' Khulna', ' Khulna'), ('Barishal', 'Barishal'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh')], max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('housesize', models.CharField(max_length=100)),
                ('bedroom', models.PositiveIntegerField(default=0)),
                ('dinning', models.PositiveIntegerField(default=0)),
                ('drawing', models.PositiveIntegerField(default=0)),
                ('bathroom', models.PositiveIntegerField(default=0)),
                ('kitchen', models.PositiveIntegerField(default=0)),
                ('balcony', models.PositiveIntegerField(default=0)),
                ('housedetail', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to=myfinal.models.filepath)),
                ('houserent', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ownerformfill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownername', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phn', models.CharField(default='', max_length=100)),
                ('housecategory', models.CharField(choices=[('flat', 'flat'), ('duplex', 'duplex'), ('commercial', ' commercial'), ('family_house', 'family_house')], max_length=100)),
                ('housename', models.CharField(max_length=100)),
                ('houserent', models.PositiveIntegerField(default=0)),
                ('img', models.ImageField(blank=True, null=True, upload_to=myfinal.models.fileimg)),
                ('imgidfont', models.ImageField(blank=True, null=True, upload_to=myfinal.models.fileimg)),
                ('imgidback', models.ImageField(blank=True, null=True, upload_to=myfinal.models.fileimg)),
                ('division', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('area', models.CharField(blank=True, max_length=250, verbose_name='Area')),
                ('housesize', models.IntegerField()),
                ('bedroom', models.PositiveIntegerField(default=0)),
                ('dinning', models.PositiveIntegerField(default=0)),
                ('drawing', models.PositiveIntegerField(default=0)),
                ('bathroom', models.PositiveIntegerField(default=0)),
                ('kitchen', models.PositiveIntegerField(default=0)),
                ('balcony', models.PositiveIntegerField(default=0)),
                ('allinfo', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Ownerformfill',
                'verbose_name_plural': 'Ownerformfill',
            },
        ),
        migrations.CreateModel(
            name='Userform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Useri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='houserate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_review', models.TextField()),
                ('info_rate', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=100)),
                ('infor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfinal.ownerformfill')),
            ],
        ),
    ]
